/* eslint-disable */

describe('监控台日志-测试', () => {
    before(() => {
        cy.visit('https://localhost')
        cy.contains('用户名').parent().find('input').type('admin')
        cy.contains('密码').parent().find('input').type('123456')
        cy.contains('登录').click()
        cy.wait(500)
        cy.contains('新建').click()
        cy.get('.el-dialog').contains('网关类型').parent().find('.el-select').click()
        cy.get('.el-select-dropdown').contains('SIM').click()
        cy.get('.el-dialog').contains('订阅合约').parent().find('.el-select').type('模拟合约')
        cy.get('.el-select-dropdown').contains('模拟合约').click()
        cy.get('.el-dialog').filter(':visible').find('button').last().click()
        cy.get('#tabAccount').click()
        cy.wait(300)
        cy.get('button').contains('新建').click()
        cy.get('.el-dialog').contains('账户ID').parent().find('input').type('testAccount')
        cy.get('.el-dialog').contains('账户类型').parent().find('.el-select').click()
        cy.get('.el-select-dropdown').filter(':visible').contains('SIM').click()
        cy.get('.el-dialog').contains('行情网关').parent().find('.el-select').click()
        cy.get('#bindedGatewayOption_SIM').click()
        cy.get('.el-dialog').filter(':visible').find('button').last().click()
        cy.wait(300)
        cy.get('#tabModule').click()
        cy.wait(300)
        cy.contains('新建').click()
        cy.get('.el-dialog').contains('模组名称').parent().find('input').type('PLAYBACKM')
        cy.get('.el-dialog').contains('模组用途').parent().find('input').click()
        cy.get('.el-select-dropdown').contains('回测').click()
        cy.get('.el-dialog').contains('交易策略').click()
        cy.get('#showDemoStrategy').click()
        cy.get('.el-dialog').contains('绑定策略').parent().find('input').click()
        cy.get('.el-select-dropdown').contains('示例-简单策略').click()
        cy.get('.el-dialog').contains('操作间隔').parent().find('input').type(600)
        cy.get('.el-dialog').contains('账户绑定').click()
        cy.get('.el-dialog').contains('绑定账号').parent().find('input').click()
        cy.get('.el-select-dropdown').contains('testAccount').click()
        cy.get('.el-dialog').contains('模组分配金额').parent().find('input').clear().type('20000')
        cy.get('.el-dialog').filter(':visible').find('.el-select').filter(':visible').last().click()
        cy.get('.el-select-dropdown').contains('模拟合约').click()
        cy.get('.el-dialog').filter(':visible').click()
        cy.get('#saveModuleSettings').click()
    })

    beforeEach(() => {
        cy.Cookies.preserveOnce('JSESSIONID')
    })

    it('可以查看平台日志', () => {
        cy.intercept('/northstar/log*').as('getLog')
        cy.get('#tabLog').click()
        cy.wait('@getLog').should('have.nested.property', 'response.statusCode', 200)
    })

    it('可以查看模组日志', () => {
        cy.get('#tabModule').click()
        cy.intercept('/northstar/log/module*').as('getMLog')
        cy.get('.el-table__row').contains('日志跟踪').click()
        cy.get('#tabLog').click()
        cy.wait('@getMLog').should('have.nested.property', 'response.statusCode', 200)
    })

    after(() => {
        cy.request('DELETE', 'https://localhost/northstar/module?name=PLAYBACKM')
        cy.request('DELETE', 'https://localhost/northstar/gateway?gatewayId=testAccount')
        cy.request('DELETE', 'https://localhost/northstar/gateway?gatewayId=SIM')
    })
})